# Generated by Django 3.1.4 on 2020-12-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdelectro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='remember',
            field=models.BooleanField(default=False),
        ),
    ]
