# Generated by Django 3.1.4 on 2020-12-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdelectro', '0002_signin_remember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='remember',
        ),
    ]
